image: docker

variables:
  IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
  IMAGE_EDGE: ${CI_REGISTRY_IMAGE}:edge
  IMAGE_LATEST: ${CI_REGISTRY_IMAGE}:latest

before_script:
  - echo "${CI_JOB_TOKEN}" | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}

stages:
  - build
  - publish

build:
  stage: build
  script: docker build --no-cache --pull -t ${IMAGE} -t ${IMAGE_EDGE} -t ${IMAGE_LATEST} . && docker push ${IMAGE}

publish edge:
  stage: publish
  script: docker push ${IMAGE_EDGE}
  only:
    - master

publish latest:
  stage: publish
  script: docker push ${IMAGE_LATEST}
  only:
    - tags
